openapi: "3.1.0"
info:
  title: "RentMyCar API V2"
  description: "API for the RentMyCar app"
  version: "1.0.0"
servers:
  - url: "https://localhost:8080"
paths:
  /auth/login:
    post:
      description: ""
      requestBody:
        content:
          '*/*':
            schema:
              $ref: "#/components/schemas/LoginRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/LoginResponse"
  /auth/register:
    post:
      description: ""
      requestBody:
        content:
          '*/*':
            schema:
              $ref: "#/components/schemas/RegisterRequest"
        required: true
      responses:
        "201":
          description: "Created"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Unit"
components:
  schemas:
    LoginRequest:
      type: "object"
      properties:
        emailAddress:
          type: "string"
        password:
          type: "string"
      required:
        - "emailAddress"
        - "password"
    LoginResponse:
      type: "object"
      properties:
        accessToken:
          type: "string"
        refreshToken:
          type: "string"
      required:
        - "accessToken"
        - "refreshToken"
    LocalDate:
      type: "object"
      properties: { }
    RegisterRequest:
      type: "object"
      properties:
        firstName:
          type: "string"
        lastName:
          type: "string"
        dateOfBirth:
          $ref: "#/components/schemas/LocalDate"
        email:
          type: "string"
        password:
          type: "string"
        address:
          type: "string"
        postalCode:
          type: "string"
        city:
          type: "string"
        phoneNumber:
          type: "string"
      required:
        - "firstName"
        - "lastName"
        - "dateOfBirth"
        - "email"
        - "password"
        - "address"
        - "postalCode"
        - "city"
        - "phoneNumber"
    Unit:
      type: "object"
      properties: { }