ktor:
  application:
    modules:
      - nl.avans.ApplicationKt.module
  deployment:
    port: 8080
jwt:
  domain: "http://localhost"
  audience: "my-audience"
  realm: "rentmycar-api"
  secret: "11e39374677c45e7a08dceead43a9ae256c775239b42852af26bda70e6b7cada"

db:
  url: "jdbc:mysql://localhost:3306/rentmycar"
  username: "root"
  password: ""
